# Generated by Django 5.1.4 on 2024-12-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={},
        ),
        migrations.RemoveField(
            model_name="device",
            name="description",
        ),
        migrations.RemoveField(
            model_name="device",
            name="project",
        ),
        migrations.RemoveField(
            model_name="device",
            name="type",
        ),
        migrations.AddField(
            model_name="device",
            name="brand",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="品牌"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="gateway",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="网关"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="纬度",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="经度",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="设备型号"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="devices/photos/",
                verbose_name="设备照片",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="product_manual",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="devices/manuals/",
                verbose_name="产品说明书",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="remote_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="远程控制码"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="remote_password",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="远程控制密码"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="subnet_mask",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="子网掩码"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP地址"
            ),
        ),
    ]
