# Generated by Django 5.1.4 on 2024-12-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_options_remove_device_description_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="projects.project",
                verbose_name="所属项目",
            ),
        ),
    ]
