# Generated by Django 5.1.4 on 2024-12-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_device_options_device_project"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="projects.project",
                verbose_name="所属项目",
            ),
        ),
    ]
