# Generated by Django 5.2.1 on 2025-08-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_device_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="设备位置"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("online", "在线"), ("offline", "离线"), ("error", "故障")],
                max_length=50,
                null=True,
                verbose_name="设备状态",
            ),
        ),
    ]
